name: Deploy Spark Scripts to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'Avance3y4-PasarARefinedYOrquestacion/scripts/**'
      - 'Avance5-Kafka/scripts/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Sync scripts to EC2
      run: |
        scp -r ./Avance3y4-PasarARefinedYOrquestacion/scripts/*.py ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/
        scp -r ./Avance5-Kafka/scripts/*.py ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/
        
    - name: Copy scripts into Spark Container
      run: |
        ssh ec2-user@${{ secrets.EC2_HOST }} "docker cp /home/ec2-user/etl_weather_s3.py spark-master:/opt/spark/etl_weather_s3.py && docker cp /home/ec2-user/etl_analytics.py spark-master:/opt/spark/etl_analytics.py && docker cp /home/ec2-user/etl_streaming_raw.py spark-master:/opt/spark/etl_streaming_raw.py && docker cp /home/ec2-user/etl_streaming_processed.py spark-master:/opt/spark/etl_streaming_processed.py && docker cp /home/ec2-user/etl_analytics_gold_unified.py spark-master:/opt/spark/etl_analytics_gold_unified.py"
